export const titles = {
  require: 'Todos los campos marcados con * son obligatorios.!',
  title: 'Pagos',
  successCreate: 'Pago creado correctamente!.',
  successUpdate: 'Pago actualizado correctamente!.',
  successDelete: 'Pago inactivado correctamente!.',
  titleDeleteModal: 'Seguro que desea eliminar el pago: ',
  titleCreate: 'Crear Pago',
  titleUpdate: 'Editar Pago',
  titleDelete: 'Inactivar Pago',
  titleNetwork: 'Red Negocios',
  labelCreate: 'Pago creado',
  labelUpdate: 'Pago actualizado',
  labelDelete: 'Pago inactivado',
  generalError: 'Ups algo salio mal: ',
  generalAction: 'Acciones',
  menuCreate: 'Agregar Pago',
  tableCell1: 'Id',
  tableCell2: 'Estado',
  tableCell3: 'Cartillas',
  tableCell4: 'Total',
  tableCell5: 'Fecha',
  tableCell6: 'Otro',
  tableCell7: 'Método',
  tableCellActions: 'Acciones',
  maxRecords: 'Registros máximos',
  noRecordsFound: 'No existen usuarios aún!',
  buttonCreate: 'Crear',
  buttonUpdate: 'Actualizar',
  buttonDelete: 'Inactivar',
  buttonCancel: 'Cancelar',
  loading: 'Cargando...',
  level1: 'Nivel 1',
  level2: 'Nivel 2',
  level3: 'Nivel 3',
  level4: 'Nivel 4',
  active: 'MIEMBRO',
  noActive: 'NO MIEMBRO',
  altImage: 'Avatar user'
};

export const inputLabels = {
  search: 'searchField',
  card: 'card',
  labelCard: 'Cartilla',
  details: 'details',
  labelDetails: 'Detalles',
  status: 'status',
  labelStatus: 'Estado',
  total: 'total',
  labelTotal: 'Total',
  paypal: 'paypal',
  labelPaypal: 'Id Orden PayPal',
  createAt: 'createAt',
  labelCreateAt: 'Fecha Creación',
  updateAt: 'updateAt',
  labelUpdateAt: 'Fecha Actualización',
  deleteAt: 'deleteAt',
  labelDeleteAt: 'Fecha Eliminación',
  placeHolderSearch: 'Buscar por Detalle, número cartilla o Id'
};
