export const gameTexts = {
  require: 'Todos los campos marcados con * son obligatorios.!',
  requireField: 'Ingrese la cantidad que desea generar!',
  successCreate: 'Partida creada correctamente!.',
  successUpdate: 'Partida actualizada correctamente!.',
  successDelete: 'Partida eliminada correctamente!.',
  successCardCreate: 'Cartilla creada correctamente!.',
  successCardUpdate: 'Cartilla actualizada correctamente!.',
  successCardDelete: 'Cartilla eliminada correctamente!.',
  titleDeleteModal: 'Seguro que desea eliminar la partida: ',
  rowsPerPage: 'Registros máximos',
  titleCreate: 'Crear Partida',
  titleUpdate: 'Editar Partida',
  titleDelete: 'Inactivar Partida',
  labelCreate: 'Partida creada',
  labelUpdate: 'Partida actualizada',
  labelDelete: 'Partida eliminada',
  labelFinish: 'Finalizar Partida',
  labelShowWinner: 'Mostar Ganador',
  generalError: 'Ups algo salio mal: ',
  generalAction: 'Acciones',
  menuCreate: 'Agregar Partida',
  tableCell0: 'ID',
  tableCell1: 'Evento',
  tableCell2: 'Fecha',
  tableCell3: 'Perfil',
  tableCell4: 'Estado',
  tableCellActions: 'Acciones',
  maxRecords: 'Registros máximos',
  noRecordsFound: 'No existen partidas aún!',
  noCardsFound: 'No existen cartillas aún para el evento seleccionado!',
  buttonCreate: 'Crear',
  buttonUpdate: 'Actualizar',
  buttonDelete: 'Eliminar',
  buttonCancel: 'Cancelar',
  buttonClose: 'Cerrar',
  loading: 'Cargando...',
  searchPlace: 'Buscar por número de cartilla',
  b: 'B',
  i: 'I',
  n: 'N',
  g: 'G',
  o: 'O',
  next: 'SIGUIENTE',
  restart: 'REINICIAR',
  actual: 'ACTUAL',
  ante: 'ANTERIOR',
  backTitle: 'Orden Números Sorteados',
  endBoard: 'PARTIDA TERMINADA',
  saveBoard: 'Guardar Tablero',
  newBoard: 'Nuevo Tablero',
  successSave: 'Tablero guardado correctamente!'
};

export const inputLabels = {
  search: 'searchField',
  name: 'name',
  labelName: 'Nombre',
  labelDate: 'Fecha',
  email: 'email',
  labelEmail: 'E-mail',
  profile: 'profile',
  labelProfile: 'Perfil',
  price: 'price',
  labelPrice: 'Precio de Cartilla',
  state: 'State',
  labelState: 'Estado',
  placeHolderSearch: 'Buscar por Nombre'
};