export const titles = {
  require: 'Todos los campos marcados con * son obligatorios.',
  successAssignment: 'Asignación realizada exitosamente.',
  successPayment: 'Pago procesado correctamente.',
  errorAssignment: 'Error al procesar la asignación.',
  errorPayment: 'Error al procesar el pago.',
  errorCardUnavailable: 'La cartilla seleccionada no está disponible.',
  titleAssignmentModal: 'Asignar Cartillas a Usuario',
  titleSummaryModal: 'Resumen de Asignación',
  rowsPerPage: 'Registros máximos',
  generalError: 'Ups, algo salió mal: ',
  generalAction: 'Acciones',
  menuAssign: 'Asignar Cartillas',
  tableCell0: 'ID',
  tableCell1: 'Nombre',
  tableCell2: 'Email',
  tableCell3: 'Estado',
  tableCellActions: 'Acciones',
  maxRecords: 'Registros máximos',
  noUsersFound: 'No se encontraron usuarios.',
  noCardsFound: 'No se encontraron cartillas disponibles.',
  buttonAssign: 'Asignar',
  buttonProcess: 'Procesar Compra',
  buttonCancel: 'Cancelar',
  buttonClose: 'Cerrar',
  buttonFinish: 'Finalizar Asignación',
  loading: 'Cargando...',
  searchUsers: 'Buscar por nombre, apellido o email',
  searchCards: 'Buscar por número de cartilla',
  stepEvent: 'Seleccionar Evento',
  stepUser: 'Seleccionar Usuario',
  stepCards: 'Seleccionar Cartillas',
  stepSummary: 'Resumen de Asignación',
  selectedCards: 'Cartillas Seleccionadas',
  totalToPay: 'Total a Pagar',
  userLabel: 'Usuario',
  eventLabel: 'Evento',
  priceLabel: 'Precio por cartilla',
  quantityLabel: 'Cantidad',
  eventDateLabel: 'Fecha del evento',
  processing: 'Procesando...',
  cardReturned: 'Esta cartilla fue devuelta y no puede ser reasignada.',
  cardReturnedWarning: 'La cartilla fue devuelta y no puede ser reasignada',
  filterReturned: 'Devueltas',
};

export const inputLabels = {
  search: 'searchField',
  userName: 'userName',
  labelUserName: 'Nombre del Usuario',
  userEmail: 'userEmail',
  labelUserEmail: 'Email del Usuario',
  eventName: 'eventName',
  labelEventName: 'Nombre del Evento',
  cardNumber: 'cardNumber',
  labelCardNumber: 'Número de Cartilla',
  availability: 'availability',
  labelAvailability: 'Disponibilidad',
  placeHolderSearchUsers: 'Buscar por nombre, apellido o email',
  placeHolderSearchCards: 'Buscar por número de cartilla'
};